# Railway Deployment Configuration
# This file configures the Railway deployment for the CapyType backend

[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm start"

[env]
  NODE_ENV = "production"

