# Render Deployment Configuration
# This file configures the Render deployment for the CapyType backend

services:
  - type: web
    name: capytype-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health

